### ISSUE TITLE
Colored output is not readable on terminal

### ISSUE THREAD

**Issue by rochacbruno** [dustypomerleau/yarra-valley#1]
My old theme `gloom`

![gloom](https://user-images.githubusercontent.com/458654/81321680-4877d480-9069-11ea-97f1-adc4d7b7e3ee.png)

Now using Yarra VAlley

![yarra_valley](https://user-images.githubusercontent.com/458654/81321703-50377900-9069-11ea-94b8-03fd04c1ba8a.png)

The output colors on temrinal are hidden by Yarra set of terminal colors defined in https://github.com/dustypomerleau/yarra-valley/blob/master/themes/yarra-valley.json#L1129-L1148

any hint on how can I solve it?

Thanks for the awesome theme

**Comment by rochacbruno** [comment]
To confirm that this is not ZSH problem, using pure bash the same problem
![yarra_bash](https://user-images.githubusercontent.com/458654/81322169-f2576100-9069-11ea-825f-7ae3fe754691.png)

**Comment by dustypomerleau** [comment]
Thanks for pointing this out. Could you download the latest update (0.23.11) and confirm that it fixes your problem before I close the issue?

**Comment by rochacbruno** [comment]
![Screenshot_2020-05-08_15-10-40](https://user-images.githubusercontent.com/458654/81435358-1f754380-913e-11ea-87f6-80e375d46b05.png)


Thanks :)
